# Generated by Django 3.2.6 on 2022-06-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0002_rename_user_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='name',
            new_name='nameee',
        ),
    ]
