# Generated by Django 3.2.6 on 2022-06-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0003_rename_name_userdata_nameee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='nameee',
            new_name='name',
        ),
    ]
