# Generated by Django 4.0.5 on 2022-07-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0004_rename_nameee_userdata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
