# Generated by Django 4.0.5 on 2022-07-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0005_userdata_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='fb/images'),
        ),
    ]
