# Generated by Django 4.0.5 on 2022-07-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0010_alter_userdata_cover_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_bio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
