# Generated by Django 4.0.5 on 2022-07-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0011_userdata_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=100)),
                ('user_mobile', models.CharField(default='', max_length=100)),
                ('user_signuppass', models.CharField(default='', max_length=100)),
                ('user_dateOFbirth', models.CharField(default='', max_length=100)),
                ('user_gender', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
