# Generated by Django 4.0.5 on 2022-07-19 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0012_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_mobile',
            new_name='user_phone',
        ),
    ]
